name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          source "$HOME/.local/bin/env" || true
          ~/.local/bin/uv --version

      - name: Sync dependencies (dev + extras)
        run: uv sync --all-extras --dev

      - name: Ruff format (check only)
        run: uv run ruff format --check .

      - name: Ruff lint
        run: uv run ruff check .

      - name: Tests
        run: |
          bash -lc '
          set -o pipefail
          set -e
          uv run pytest -q || code=$?
          if [ "${code:-0}" -eq 5 ]; then
            echo "No tests found; treating as success."
            exit 0
          else
            exit ${code:-0}
          fi
          '
