name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sync deps
        run: uv sync --all-extras --dev

      - name: Ruff format (check only)
        run: uv run ruff format --check .

      - name: Ruff lint
        run: uv run ruff check .

      - name: Tests
        run: uv run pytest -q
